### ISSUE TITLE
Feature to view topic tags along with question data

### ISSUE THREAD

**Issue by akki251** [Bishalsarang/Leetcode-Questions-Scraper#3]
The json data is pretty good, but I was thinking could you also implement a field TOPICS of array, which contains topic tags for each question.

**Comment by Bishalsarang** [comment]
Currently, I'm busy with other stuffs. So I won't be able to implement it soon.
But you open the PR for this which is straightforward. There seems to be a `topicTags` key for each question.
  ```
  {
        "acRate": 32.134976525374064,
        "difficulty": "MEDIUM",
        "freqBar": null,
        "frontendQuestionId": "50",
        "isFavor": false,
        "paidOnly": false,
        "status": "NOT_STARTED",
        "title": "Pow(x, n)",
        "titleSlug": "powx-n",
        "topicTags": [
            {
                "name": "Math",
                "id": "VG9waWNUYWdOb2RlOjg=",
                "slug": "math"
            },
            {
                "name": "Recursion",
                "id": "VG9waWNUYWdOb2RlOjMx",
                "slug": "recursion"
            }
        ],
        "hasSolution": true,
        "hasVideoSolution": false
    }
```

What you may have to is simply update this line to support tags.
https://github.com/Bishalsarang/Leetcode-Questions-Scraper/blob/610968328fd929cfaa8edb7d4dd0696bbccb1d30/main.py#L58

It would be great to have tags as chip similar to what leetcode shows.

Feel free to ask questions if you have any confusion.

**Comment by akki251** [comment]
Alright got it, Thanks👍
