### ISSUE TITLE
Feature: Updating the backend system to rely on GraphQL API instead of Web Scraping

### ISSUE THREAD

**Issue by thekodeking** [Bishalsarang/Leetcode-Questions-Scraper#5]
### Description

This Issue is more like a suggestion that might make this project more awesome.

I have been working on a similar project and, I have noticed that you are relying on web scraping instead of using the Leetcode GraphQL API. Using an API will boost the speed of your backend process when compared to web scraping.

Feel free to close the issue👍🏼.

**Comment by Bishalsarang** [comment]
Sure, will look into it. The primary reason for relying on web scraping is also to maintain the layouts and CSS from leetcode instead of building one myself. Will be switching to graphql if those cases can be handled properly.

Thanks for the suggestion.
