### ISSUE TITLE
Getting None for question description

### ISSUE THREAD

**Issue by NarutoUchiha39** [Bishalsarang/Leetcode-Questions-Scraper#6]
Getting None constantly for question description

**Comment by Bishalsarang** [comment]
Thanks for raising the issue. Maybe some markup has changed in Leetcode.
Will look into it.

**Comment by Bishalsarang** [comment]
The issue has been fixed in https://github.com/Bishalsarang/Leetcode-Questions-Scraper/commit/1bf9474b8f61c89aafdfca0acd6d9b33386a49fb . Please let me know if you are still having the issue
